#!/bin/bash
ispal () {
  case ${#1} in
    1) ;;
    2) (( ${1::1} == ${1:1} )) ;;
    *) (( ${1::1} == ${1:(-1)} )) && ispal "${1:1:${#1}-2}" ;;
  esac
}

max=0
for i in {100..999}; do
  for (( j = i; j < 1000; j++)); do
    if (( i * j > max )); then
      ispal "$((i * j))" && max=$((i * j))
    fi
  done
done
echo "$max"
