#!/bin/bash
LANG=C
ispal () {
  case ${#1} in
    1) ;;
    2) (( ${1::1} == ${1:1} )) ;;
    *) (( ${1::1} == ${1:(-1)} )) && ispal "${1:1:${#1}-2}" ;;
  esac
}

max=0
for i in {999..100}; do
  (( i * 999 < max )) && break
  for (( j = 999; j >= i; j--)) do
    if (( i * j > max )); then
      if ispal "$((i * j))"; then
        max=$((i * j))
        break
      fi
    else break
    fi
  done
done
echo "$max"
