#!/bin/bash

# a+b+sqrt(a^2+b^2) = 1000
# a+b-1000 = -sqrt(a^2+b^2)
# (a+b-1000)^2 = a^2+b^2
# a^2+b^2+1000000+2ab-2000a-2000b = a^2+b^2
# 1000000+2ab-2000a-2000b = 0
# 1000000+2ab = 2000(a+b)
# 500000+ab = 1000(a+b)

for (( i = 1; i < 1000; i++ )); do
  for (( j = 1; j <= i; j++ )); do
    if (( 500000 + i * j == 1000 * (i+j) )); then
      echo "$(( i * j * ( 1000 - i - j ) ))"
      exit
    fi
  done
done
